site_name: McMahon GOTY

nav:
  - Home: index.md
  - 2020:
    - John: 2020/john.md
    - Steve: 2020/steve.md
    - Dave: 2020/dave.md
    - Dan: 2020/dan.md

theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: teal
    accent: cyan

repo_url: https://github.com/dan-mcm/goty
repo_name: McMahon GOTY
edit_uri: edit/master/goty

markdown_extensions:
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.mark
  - smarty
